# Generated by Django 3.2.8 on 2021-10-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211016_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
