# Generated by Django 3.2.12 on 2023-03-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_database_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('transcription_factor', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('family', models.CharField(max_length=256)),
                ('accession_number', models.CharField(max_length=256)),
                ('function', models.CharField(max_length=256)),
                ('pathway_category', models.CharField(max_length=256)),
                ('phenotype', models.CharField(max_length=256)),
                ('experimental_method', models.CharField(max_length=256)),
                ('references', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('publication_link', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.species')),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
            },
        ),
    ]
