# Generated by Django 3.2.12 on 2023-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gene_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('gene_name', models.CharField(max_length=256)),
                ('publication_year', models.PositiveBigIntegerField()),
                ('phone_number', models.PositiveBigIntegerField(null=True)),
                ('pubmed_id', models.CharField(blank=True, max_length=256)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'GeneSuggestion',
                'verbose_name_plural': 'GeneSuggestions',
            },
        ),
    ]
