# Generated by Django 3.2.12 on 2023-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_genesuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='accession_number',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='family',
        ),
        migrations.AlterField(
            model_name='genesuggestion',
            name='publication_year',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genesuggestion',
            name='pubmed_id',
            field=models.CharField(max_length=256),
        ),
    ]
