# Generated by Django 3.2.12 on 2023-03-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230305_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='transcription_factor',
        ),
    ]
