# Generated by Django 3.2.8 on 2023-03-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_gene_transcription_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='year',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='genesuggestion',
            old_name='comments',
            new_name='contributor_comments',
        ),
        migrations.RenameField(
            model_name='genesuggestion',
            old_name='email',
            new_name='contributor_email',
        ),
        migrations.RenameField(
            model_name='genesuggestion',
            old_name='gene_name',
            new_name='contributor_name',
        ),
        migrations.RemoveField(
            model_name='genesuggestion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='genesuggestion',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='genesuggestion',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='genesuggestion',
            name='pubmed_id',
        ),
        migrations.AddField(
            model_name='gene',
            name='linked_suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genesuggestion'),
        ),
        migrations.AddField(
            model_name='genesuggestion',
            name='contributor_phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
