# Generated by Django 3.2.8 on 2023-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230322_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
