# Generated by Django 3.2.8 on 2023-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gene_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='publication_year',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gene',
            name='references',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
