# Generated by Django 3.2.8 on 2023-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230322_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='genesuggestion',
            name='contributor_comments',
            field=models.TextField(blank=True),
        ),
    ]
