# Generated by Django 3.2.8 on 2023-04-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230408_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneBlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_type', models.CharField(choices=[('n', 'nucleotide'), ('p', 'protein')], default='p', max_length=1)),
                ('fasta', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gene')),
            ],
        ),
    ]
