# Generated by Django 3.2.8 on 2023-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_geneblast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastDatabaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_type', models.CharField(choices=[('n', 'nucleotide'), ('p', 'protein')], default='n', max_length=1, unique=True)),
                ('fasta', models.FileField(upload_to='backend_media/blast/')),
            ],
            options={
                'verbose_name': 'BlastDatabaseFile',
                'verbose_name_plural': 'BlastDatabaseFiles',
            },
        ),
        migrations.DeleteModel(
            name='GeneBlast',
        ),
    ]
