# Generated by Django 3.2.8 on 2023-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230429_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastdatabasefile',
            name='fasta',
            field=models.FileField(upload_to='blast/'),
        ),
    ]
