# Generated by Django 3.2.8 on 2023-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_blastdatabasefile_makeblastdb_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_fasta', models.FileField(upload_to='blast_search/')),
                ('fasta_type', models.CharField(choices=[('n', 'nucleotide'), ('p', 'protein')], default='n', max_length=1)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='blast_search/')),
            ],
        ),
    ]
